post/urls.py
from django.urls import path
from.views import HomePageView,UsuariosView, UpdatePageView,DeletePageView
from post.views import CreateView,DetailPageView

urlpatterns = [
    path("", HomePageView.as_view(), name= "post"),
    path("usuarios",UsuariosView.as_view(),name="usuarios"),
    path("post/create",CreateView.as_view(),name="create"),
    path("post/detail/<int:pk>",DetailPageView.as_view(),name="detail"),
    path("post/detail/<int:pk>/update",UpdatePageView.as_view(),name="update"),
    path("post/detail/<int:pk>/delete",DeletePageView.as_view(),name="delete"),
]

registro/urls.py
from django.urls import path,include
from registro.views import *

urlpatterns=[

    path("accounts/",include("django.contrib.auth.urls")),
    path("",portada,name="pagina_principal"),
    path("signup/",SignupView.as_view(),name="signup")

]

twitter2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("pages/", include('post.urls')),
    path("",include('registro.urls'))
]


if settings.DEBUG:

    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models

# Create your models here.

class Post (models.Model):
    titulo = models.CharField(max_length=40)
    descripcion = models.TextField()
    imagen=models.ImageField(upload_to="photos", blank=True)
    precio=models.FloatField(default=True)
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE,blank=True,default=True)


    class Meta:
        verbose_name_plural = "Publicaciones"

    def __str__(self):
        return self.titulo 
    
class Personas(models.Model):
    imagen=models.ImageField(upload_to="photos",blank= True)
    nombre=models.CharField(max_length=50)
    descripcion=models.CharField(max_length=200)

    class meta:
        verbose_name_plural = "Personal"

    def __str__(self):
        
        return self.nombre

registro/models.py
from django.db import models

# Create your models here.

post/views.py
from django.views.generic.edit import DeleteView,UpdateView
from django.shortcuts import render
from django.views.generic import ListView
from.models import Post, Personas
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.views.generic import DetailView
# Create your views here.

class HomePageView(ListView):
    template_name= "post.html"
    model= Post 


class UsuariosView(ListView):
    template_name = "usuarios.html"
    model= Personas

class CreateView(CreateView):

    model=Post
    template_name="create.html"
    fields=["titulo","descripcion","imagen","precio"]
    success_url =reverse_lazy("post")

class DetailPageView(DetailView):
    model=Post
    template_name="detail.html"

class UpdatePageView(DeleteView):
    template_name="update.html"
    model=Post
    fields=["titulo","descripcion","imagen","precio"]
    sucess_url=reverse_lazy("post")

class DeletePageView(DeleteView):
    template_name="delete.html"
    model=Post
    success_url = reverse_lazy("post")

registro/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def portada(request):

    return render(request,"registration/portada.html")

class SignupView(CreateView):
    form_class=UserCreationForm
    succes_url=reverse_lazy("login")
    template_name="registration/signup.html"

templates/create.html
<div style="display: flex; justify-content: center; align-items: center; height: 100vh; background: linear-gradient(to bottom, #4169E1, #8B0000);">
    <div style="background-color: #FFFDD0; border-radius: 15px; padding: 30px; box-shadow: 0 6px 12px rgba(0,0,0,0.15); width: 60%;">
        <form action="" method="post" enctype="multipart/form-data" style="text-align: center;">
            {% csrf_token %}
            {{ form.as_p }}
            <div style="text-align: center;">
                <input type="submit" value="Crear" style="background-color: #D2B48C; color: white; padding: 12px 25px; border: none; border-radius: 5px; cursor: pointer; font-size: 16px;">
            </div>
        </form>
    </div>
</div>

<style>
    body {
        margin: 0;
        font-family: Arial, sans-serif; /* Fuente básica */
    }

    label {
        font-weight: bold; /* Negrita para las etiquetas */
    }

    input[type="text"], textarea {
        width: 100%; 
        padding: 10px; 
        border: 1px solid #ccc; 
        border-radius: 5px; 
        box-sizing: border-box; 
        margin-top: 5px; 
        margin-bottom: 20px;

templates/delete.html
<div style="display: flex; justify-content: center; align-items: center; height: 100vh; background-color: #800080;">
    <div style="background-color: #ffebeb; border-radius: 15px; padding: 30px; box-shadow: 0 6px 12px rgba(0,0,0,0.15); width: 45%;">
        <form action="" method="post" style="text-align: center;">
            {% csrf_token %}
            <p style="color: #b30000;">Seguro que quieres eliminar <strong>{{ post.title }}</strong>?</p>
            <input type="submit" value="Delete" style="background-color: #b30000; color: white; padding: 12px 25px; border: none; border-radius: 5px; cursor: pointer; font-size: 16px;">
        </form>
    </div>
</div>

<style>
    body {
        margin: 0;
        font-family: Arial, sans-serif; /* Fuente básica */
    }

    p {
        font-weight: bold; /* Negrita para el texto */
    }
</style>

templates/detail.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalle del Producto</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #d3d3d3; /* Fondo gris claro */
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .product-card {
            background-color: #b0e0e6; /* Fondo azul cristalino */
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
            text-align: center;
            max-width: 400px;
            width: 100%;
        }
        .product-image img {
            max-width: 100%;
            border-radius: 10px;
        }
        .product-title {
            font-size: 24px;
            margin-bottom: 10px;
            color: #333;
        }
        .product-price {
            font-size: 20px;
            margin-bottom: 10px;
            color: #d32f2f; /* Color rojo para el precio */
        }
        .product-description {
            font-size: 16px;
            margin-bottom: 20px;
            color: #555;
        }
        .product-card button {
            background-color: #DAA520; /* Color dorado */
            border: none;
            padding: 10px 20px;
            color: white;
            font-size: 16px;
            margin: 5px;
            cursor: pointer;
            border-radius: 5px;
        }
        .product-card button:hover {
            background-color: #b8860b; /* Dorado oscuro al pasar el ratón */
        }
    </style>
</head>
<body>
    <div class="product-card">
        <div class="product-image">
            {% if post.imagen %}
            <img src="{{post.imagen.url}}" alt="Imagen del Producto">
            {% endif %}
        </div>
        
        <h2 class="product-title">{{post.titulo}}<h2>
        <p class="product-price">${{post.precio}}</p>
        <p class="product-description">{{post.descripcion}}</p>
        <button>Añadir al Carrito</button>
        <button>Comprar Ahora</button>
    </div>
    <a href="{% url 'update' post.pk %}">Actualizar</a>
    <a href="{% url 'delete' post.pk %}">Borrar</a>
</body>
</html>

templates/home.html
{% include 'navbar.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'post' %}">Publicaciones</a>
    <a href="{% url 'usuarios' %}">Usuarios</a>
</body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Navbar Interactiva</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .navbar {
            display: flex;
            justify-content: space-around;
            align-items: center;
            background-color: #007BFF;
            padding: 10px 20px;
            border-radius: 50px;
        }
        .navbar a {
            color: #fff;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 20px;
            transition: background-color 0.3s ease;
        }
        .navbar a:hover {
            background-color: #0056b3;
        }
        .navbar .active {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <a href="{% url 'post' %}">Home</a>
        <a href="{% url 'create' %}">Create</a>
        
        <form  method="post" action="{% url 'logout' %}" >
                {% csrf_token %}
                <input class="navbar" type="submit" value="Logout" >
        </form>
    </div>
</body>
</html>

templates/post.html
{% include 'navbar.html' %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Publicación de Productos</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
        }
        .container {
            width: 80%;
            margin: auto;
            overflow: hidden;
        }
        header {
            background: #333;
            color: #fff;
            padding-top: 30px;
            min-height: 70px;
            border-bottom: #77a5d8 3px solid;
        }
        header h1 {
            text-align: center;
            text-transform: uppercase;
            margin: 0;
        }
        .product-card {
            background: #fff;
            padding: 20px;
            margin: 20px 0;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        .product-image img {
            max-width: 100%;
            border-radius: 5px;
        }
        .product-title {
            font-size: 24px;
            margin-bottom: 10px;
        }
        .product-description {
            font-size: 18px;
            color: #555;
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <h1>Catálogo de Productos</h1>
        </div>
    </header>
    {% for post in post_list %}
    
    <div class="container">
        <div class="product-card">
            <div class="product-image">
                <img src="ruta-de-la-imagen.jpg" alt="Imagen del Producto">
            </div>
            <h2 class="product-title"><a href="{% url 'detail' post.pk %}">{{ post.titulo }}</a></h2>
            <p class="product-description">{{post.descripcion}}</p>
        </div>
    </div>
    {% endfor %}
</body>
</html>


<a href="{% url 'usuarios' %}">Dashboard de usuarios</a>
<a href="{% url 'create' %}">create</a>

templates/update.html
<form action=""method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{form.as_p}}

    <input type="submit" value="Actualizar">

</form>

templates/usuarios.html
<!DOCTYPE html>
<html>
<head>
    <title>Mi Primera Tabla</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }

        tr:nth-child(even) {
            background-color:   
 #f2f2f2;
        }

        th {
            background-color: #4CAF50;
            color: white;
        }
    </style>
</head> 

<body>

<h2>Mi Tabla de Frutas</h2>

<table>
  <tr>
    <th>Imagen</th>
    <th>Nombre</th>
    <th>Descripcion</th>
  </tr>
 
<tbody>
        {% for usuarios in personas_list %}
      <tr>
        <td><img src="{{ usuarios.imagen.url }}" width="300" height="300"></td>
        <td>{{ usuarios.nombre }}</td>
        <td>{{ usuarios.descripcion }}</td>
      </tr>

      {% endfor %}
    
</tbody>
  
</table>

</body>
</html>